Prevent ZFS components from restarting on every deploy (#8317)
* Exit ZFS init script on any error
* Update metadata labels on ZFS init daemonset to match selector labels

Signed-off-by: Jesse Nelson <jesse@swirldslabs.com>

diff --git a/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml b/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
--- a/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
+++ b/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
@@ -2,7 +2,7 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  labels: {{ include "hedera-mirror-common.labels" . | nindent 4 }}
+  labels: {{ include "hedera-mirror-common.selectorLabels" . | nindent 4 }}
     app: zfs-init
   name: {{ .Release.Name }}-zfs-init
   namespace: {{ include "hedera-mirror-common.namespace" . }}
@@ -18,7 +18,7 @@ data:
   entrypoint.sh: |
     #!/usr/bin/env bash
     
-    set -uxo pipefail
+    set -euxo pipefail
     
     # Constants
     NODE_ID_LABEL="openebs.io/nodeid"
@@ -43,7 +43,6 @@ data:
     ZONE="$(curl -sS http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google' | awk -F  "/" '{print $NF}')"
     NODE_LABELS="$(kubectl get node ${NODE_NAME} -o jsonpath='{.metadata.labels}')"
     CITUS_ROLE="$(echo "${NODE_LABELS}" | jq --arg ROLE_LABEL "${ROLE_LABEL}" -r '.[$ROLE_LABEL]')"
-    NODE_ID="$(echo "${NODE_LABELS}" | jq --arg NODE_ID_LABEL "${NODE_ID_LABEL}" -r '.[$NODE_ID_LABEL]')"
 
     ATTEMPT_COUNT=1
     while [[ "${CITUS_ROLE}" == "null" ]]
@@ -58,7 +57,6 @@ data:
       echo "Retrying label GET attempt: ${ATTEMPT_COUNT}"
       NODE_LABELS="$(kubectl get node ${NODE_NAME} -o jsonpath='{.metadata.labels}')"
       CITUS_ROLE="$(echo "${NODE_LABELS}" | jq --arg ROLE_LABEL "${ROLE_LABEL}" -r '.[$ROLE_LABEL]')"
-      NODE_ID="$(echo "${NODE_LABELS}" | jq --arg NODE_ID_LABEL "${NODE_ID_LABEL}" -r '.[$NODE_ID_LABEL]')"
     done
     # Ensure node status config map is created
     until (kubectl get configmap -o json -n "${K8S_NAMESPACE}" "${CONFIG_MAP_NAME}" &> /dev/null)
@@ -142,12 +140,22 @@ data:
       MODIFIED_CONFIG_MAP="$(echo "${MODIFIED_CONFIG_MAP}" | jq --arg KEY "${CONFIG_MAP_KEY}" '.data[$KEY]=(.data[$KEY]|tojson)')"
     
       echo "patching $CONFIG_MAP_NAME with $MODIFIED_CONFIG_MAP"
-      kubectl patch configmap $CONFIG_MAP_NAME \
-      -n $K8S_NAMESPACE \
-      --type merge \
-      -p "${MODIFIED_CONFIG_MAP}"
-      COMMAND_STATUS=$?
+      if (kubectl patch configmap $CONFIG_MAP_NAME -n $K8S_NAMESPACE --type merge -p "${MODIFIED_CONFIG_MAP}")
+      then
+        echo "Successfully patched config map"
+        COMMAND_STATUS=0
+      else
+        COMMAND_STATUS=$?
+        echo "Conflict patching config map. Retrying ..."
+      fi
     done
+    
+    NODE_ID="$(echo "${THIS_NODE_CONFIG}" | jq -r '.nodeId')"
+    if [[ "${NODE_ID}" == "null" ]]
+    then
+      echo "Unable to determine correct node id. Exiting ..."
+      exit 1
+    fi
     
     DISK_NAME="${DISK_PREFIX}-${NODE_ID}-zfs"
     DISK_SIZE="$(echo "${THIS_NODE_CONFIG}" | jq -r '.diskSize')"
@@ -168,21 +176,16 @@ data:
 
     if (! gcloud compute instances describe "${NODE_NAME}" --zone "${ZONE}" --format '(disks[].source)' | grep "${DISK_NAME}" > /dev/null); then
         echo "Attaching ${DISK_NAME} to ${NODE_NAME}"
-        gcloud compute instances attach-disk "${NODE_NAME}" --device-name=sdb --disk "${DISK_NAME}" --zone "${ZONE}"
-        COMMAND_STATUS=$?
-        ATTACH_ATTEMPTS=1
-        until [[ ${COMMAND_STATUS} -eq 0 || ${ATTACH_ATTEMPTS} -ge 13 ]]; do
+        ATTACH_ATTEMPTS=0
+        until (gcloud compute instances attach-disk "${NODE_NAME}" --device-name=sdb --disk "${DISK_NAME}" --zone "${ZONE}"); do
+          ATTACH_ATTEMPTS=$((ATTACH_ATTEMPTS+1))
+          if [[ $ATTACH_ATTEMPTS -ge 15 ]]; then
+              echo "Unable to attach ${DISK_NAME} to ${NODE_NAME} in ${ZONE} ater ${ATTACH_ATTEMPTS} attempts. Exiting ..."
+              exit 1
+          fi
           echo "Unable to attach ${DISK_NAME} to ${NODE_NAME} attempts ${ATTACH_ATTEMPTS}. waiting ..." 
           sleep 30
-          gcloud compute instances attach-disk "${NODE_NAME}" --device-name=sdb --disk "${DISK_NAME}" --zone "${ZONE}"
-          COMMAND_STATUS=$?
-          ATTACH_ATTEMPTS=$((ATTACH_ATTEMPTS+1))
         done
-    
-        if [[ $COMMAND_STATUS != 0 ]]; then
-          echo "Unable to attach ${DISK_NAME} to ${NODE_NAME} in ${ZONE}";
-          exit 1
-        fi
     else
         echo "${DISK_NAME} is already attached to ${NODE_NAME}"
     fi
