update zfs deployment
Signed-off-by: Jesse Nelson <jesse@swirldslabs.com>

diff --git a/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml b/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
--- a/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
+++ b/charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
@@ -28,16 +28,40 @@ data:
     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
      apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - 
     apt-get update -y
-    apt-get install google-cloud-cli -y
+    apt-get install google-cloud-cli jq -y
 
     echo "Getting node metadata"
     NODE_NAME="$(curl -sS http://metadata.google.internal/computeMetadata/v1/instance/name -H 'Metadata-Flavor: Google')"
     ZONE="$(curl -sS http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google' | awk -F  "/" '{print $4}')"
-    echo "Getting labels"
-    LABELS="$(gcloud compute instances describe $NODE_NAME --zone=$ZONE --flatten="metadata.kube-labels[]")"
-    CITUS_ROLE="$(echo $LABELS | grep -o 'citus-role[^, }]*' | sed -n 's/.*citus-role=\(.*\).*/\1/p')"
-    DISK_NAME="$NODE_NAME-zfs"
-    echo "Setting up disk $DISK_NAME for $CITUS_ROLE"
+    
+    # Point to the internal API server hostname
+    APISERVER=https://kubernetes.default.svc
+    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
+    TOKEN=$(cat ${SERVICEACCOUNT}/token)
+    CACERT=${SERVICEACCOUNT}/ca.crt
+    
+    echo "Getting node labels"
+    NODE_LABELS="$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/nodes/${NODE_NAME})"
+    CITUS_ROLE="$(echo $NODE_LABELS | jq -r '.metadata.labels["citus-role"]')"
+    NODE_ID="$(echo $NODE_LABELS | jq -r '.metadata.labels["openebs.io/nodeid"]')"
+    ATTEMPT_COUNT=1
+    while [[ "$CITUS_ROLE" == "null" || "$NODE_ID" == "null" ]]
+    do
+      if [[ $ATTEMPT_COUNT -ge 13 ]]
+      then
+        echo "Timed out waiting for labels please set citus-role and openebs.io/nodeid"
+        exit 1
+      fi
+      ATTEMPT_COUNT=$((ATTEMPT_COUNT+1))
+      echo "Retrying label GET attempt: $ATTEMPT_COUNT"
+      NODE_LABELS="$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/nodes/${NODE_NAME})"
+      CITUS_ROLE="$(echo $NODE_LABELS | jq -r '.metadata.labels["citus-role"]')"
+      NODE_ID="$(echo $NODE_LABELS | jq -r '.metadata.labels["openebs.io/nodeid"]')"
+      sleep 10
+    done
+    
+    DISK_NAME="$NODE_ID-zfs"
+    echo "Setting up disk $DISK_NAME for $CITUS_ROLE on zfs node $NODE_ID"
     
     if [[ "$CITUS_ROLE" == *"worker"* ]]; then
         DISK_SIZE=$DISK_SIZE_WORKER
@@ -52,9 +76,20 @@ data:
         echo "$DISK_NAME already exists for $CITUS_ROLE"
     fi
 
-    if ! gcloud compute instances describe "$NODE_NAME" --zone "$ZONE" --format '(disks[].source)' | grep "$DISK_NAME" > /dev/null; then
-        echo "Attaching $DISK_NAME to $NODE_NAME"
-        gcloud compute instances attach-disk "$NODE_NAME" --device-name=sdb --disk "$DISK_NAME" --zone "$ZONE"
+    if ! gcloud compute instances describe "$NODE_NAME" --zone "$ZONE" --format '(disks[].source)' | grep "$DISK_NAME" > /dev/null; then        
+        ATTACH_ATTEMPTS=0
+        COMMAND_STATUS=1
+        until [[ $COMMAND_STATUS -eq 0 || $ATTACH_ATTEMPTS -ge 13 ]]; do
+          gcloud compute instances attach-disk "$NODE_NAME" --device-name=sdb --disk "$DISK_NAME" --zone "$ZONE"
+          COMMAND_STATUS=$?
+          ATTACH_ATTEMPTS=$((ATTACH_ATTEMPTS+1))
+          sleep 10
+        done
+    
+        if [[ $COMMAND_STATUS != 0 ]]; then
+          echo "Unable to attach $DISK_NAME to $NODE_NAME in $ZONE";
+          exit 1
+        fi
     else
         echo "$DISK_NAME is already attached to $NODE_NAME"
     fi
