wait for access-node to be ready and all data nodes to be added to access node
Signed-off-by: Xin Li <xin.li@swirlds.com>
Signed-off-by: Xin Li <xin.li@hedera.com>

diff --git a/charts/hedera-mirror/templates/job-timescaledb-init.yaml b/charts/hedera-mirror/templates/job-timescaledb-init.yaml
--- a/charts/hedera-mirror/templates/job-timescaledb-init.yaml
+++ b/charts/hedera-mirror/templates/job-timescaledb-init.yaml
@@ -21,7 +21,15 @@ spec:
             - |
               set -e
 
-              while ! pg_isready -U postgres -h {{ include "hedera-mirror.dbHost" . }}-data; do sleep 1; done;
+              # wait for the access node to allow connections
+              while ! pg_isready -U postgres -h {{ include "hedera-mirror.dbHost" . }}; do sleep 1; done;
+
+              # wait for all data nodes to be added to access node
+              while true; do
+                count=$(echo "${GET_DATA_NODES_COUNT_COMMAND}" | psql -d "${ACCESS_SVC_CONNSTR_POSTGRES}" --file=- --set ON_ERROR_STOP=1 -At)
+                [ "$count" -eq "{{ .Values.timescaledb.dataNodes }}" ] && break || sleep 1
+              done
+
               psql --echo-queries -d "${ACCESS_SVC_CONNSTR_POSTGRES}" --set ON_ERROR_STOP=1 -f ${DB_INIT_DIR}/users_v2.sql
               echo 'Completed db initialization and user creation for mirror node'
 
@@ -39,6 +47,8 @@ spec:
               value: host={{ include "hedera-mirror.dbHost" . }} dbname={{ .Values.importer.config.hedera.mirror.importer.db.name }} user={{ .Values.importer.config.hedera.mirror.importer.db.owner }} connect_timeout=3 sslmode=disable password={{ .Values.importer.config.hedera.mirror.importer.db.ownerPassword }}
             - name: DB_INIT_DIR
               value: /usr/etc/db-init
+            - name: GET_DATA_NODES_COUNT_COMMAND
+              value: select count(*) from pg_foreign_server
           volumeMounts:
             - name: timescaledb-init-volume
               mountPath: /usr/etc/db-init
